name: Sync Upstream Changes

on:
  schedule:
    - cron: '0 * * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
    inputs:
      upstream_url:
        description: 'Upstream repository URL'
        required: false
        type: string
      upstream_branch:
        description: 'Upstream branch to sync from'
        required: false
        type: string
      target_branch:
        description: 'Target branch in this repo'
        required: false
        type: string

env:
  DEFAULT_UPSTREAM_URL: "https://github.com/lvgl/lvgl.git"  # Replace with actual upstream repo
  DEFAULT_UPSTREAM_BRANCH: "master"  # Replace with actual upstream branch
  DEFAULT_TARGET_BRANCH: "master"  # Replace with actual target branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Upstream and Target Branch
        run: |
          if [ -z "${{ github.event.inputs.upstream_url }}" ]; then
            echo "UPSTREAM_URL=${{ env.DEFAULT_UPSTREAM_URL }}" >> $GITHUB_ENV
          else
            echo "UPSTREAM_URL=${{ github.event.inputs.upstream_url }}" >> $GITHUB_ENV
          fi

          if [ -z "${{ github.event.inputs.upstream_branch }}" ]; then
            echo "UPSTREAM_BRANCH=${{ env.DEFAULT_UPSTREAM_BRANCH }}" >> $GITHUB_ENV
          else
            echo "UPSTREAM_BRANCH=${{ github.event.inputs.upstream_branch }}" >> $GITHUB_ENV
          fi

          if [ -z "${{ github.event.inputs.target_branch }}" ]; then
            echo "TARGET_BRANCH=${{ env.DEFAULT_TARGET_BRANCH }}" >> $GITHUB_ENV
          else
            echo "TARGET_BRANCH=${{ github.event.inputs.target_branch }}" >> $GITHUB_ENV
          fi

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Repository
        run: |
          git remote add upstream ${{ env.UPSTREAM_URL }}
          git fetch upstream ${{ env.UPSTREAM_BRANCH }}

      - name: Merge Upstream Changes
        run: |
          git merge --ff-only upstream/${{ env.UPSTREAM_BRANCH }}
          git push origin ${{ env.TARGET_BRANCH }}

      - name: Handle Merge Conflicts
        if: failure()
        run: echo "Merge conflict detected. Please resolve manually."
